//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthWind_WebApp.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerIdField, value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CustomerTitle {
            get {
                return this.CustomerTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerTitleField, value) != true)) {
                    this.CustomerTitleField = value;
                    this.RaisePropertyChanged("CustomerTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderDetails", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class OrderDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int OrderIDField;
        
        private System.Nullable<int> EmployeeIDField;
        
        private System.Nullable<System.DateTime> OrderDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((this.OrderIDField.Equals(value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.Nullable<int> EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((this.EmployeeIDField.Equals(value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<System.DateTime> OrderDate {
            get {
                return this.OrderDateField;
            }
            set {
                if ((this.OrderDateField.Equals(value) != true)) {
                    this.OrderDateField = value;
                    this.RaisePropertyChanged("OrderDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Products", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Products : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        private decimal UnitPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal UnitPrice {
            get {
                return this.UnitPriceField;
            }
            set {
                if ((this.UnitPriceField.Equals(value) != true)) {
                    this.UnitPriceField = value;
                    this.RaisePropertyChanged("UnitPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int EmployeeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int EmployeeId {
            get {
                return this.EmployeeIdField;
            }
            set {
                if ((this.EmployeeIdField.Equals(value) != true)) {
                    this.EmployeeIdField = value;
                    this.RaisePropertyChanged("EmployeeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name FirstCustomerResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FirstCustomer", ReplyAction="*")]
        NorthWind_WebApp.ServiceReference1.FirstCustomerResponse FirstCustomer(NorthWind_WebApp.ServiceReference1.FirstCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FirstCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<NorthWind_WebApp.ServiceReference1.FirstCustomerResponse> FirstCustomerAsync(NorthWind_WebApp.ServiceReference1.FirstCustomerRequest request);
        
        // CODEGEN: Generating message contract since element name LastCustomerResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LastCustomer", ReplyAction="*")]
        NorthWind_WebApp.ServiceReference1.LastCustomerResponse LastCustomer(NorthWind_WebApp.ServiceReference1.LastCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LastCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<NorthWind_WebApp.ServiceReference1.LastCustomerResponse> LastCustomerAsync(NorthWind_WebApp.ServiceReference1.LastCustomerRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NextCustomer", ReplyAction="*")]
        NorthWind_WebApp.ServiceReference1.NextCustomerResponse NextCustomer(NorthWind_WebApp.ServiceReference1.NextCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NextCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<NorthWind_WebApp.ServiceReference1.NextCustomerResponse> NextCustomerAsync(NorthWind_WebApp.ServiceReference1.NextCustomerRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PrevCustomer", ReplyAction="*")]
        NorthWind_WebApp.ServiceReference1.PrevCustomerResponse PrevCustomer(NorthWind_WebApp.ServiceReference1.PrevCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PrevCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<NorthWind_WebApp.ServiceReference1.PrevCustomerResponse> PrevCustomerAsync(NorthWind_WebApp.ServiceReference1.PrevCustomerRequest request);
        
        // CODEGEN: Generating message contract since element name ID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_Customer", ReplyAction="*")]
        NorthWind_WebApp.ServiceReference1.Add_CustomerResponse Add_Customer(NorthWind_WebApp.ServiceReference1.Add_CustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_Customer", ReplyAction="*")]
        System.Threading.Tasks.Task<NorthWind_WebApp.ServiceReference1.Add_CustomerResponse> Add_CustomerAsync(NorthWind_WebApp.ServiceReference1.Add_CustomerRequest request);
        
        // CODEGEN: Generating message contract since element name ID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_Customer", ReplyAction="*")]
        NorthWind_WebApp.ServiceReference1.Update_CustomerResponse Update_Customer(NorthWind_WebApp.ServiceReference1.Update_CustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_Customer", ReplyAction="*")]
        System.Threading.Tasks.Task<NorthWind_WebApp.ServiceReference1.Update_CustomerResponse> Update_CustomerAsync(NorthWind_WebApp.ServiceReference1.Update_CustomerRequest request);
        
        // CODEGEN: Generating message contract since element name ID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete_Customer", ReplyAction="*")]
        NorthWind_WebApp.ServiceReference1.Delete_CustomerResponse Delete_Customer(NorthWind_WebApp.ServiceReference1.Delete_CustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete_Customer", ReplyAction="*")]
        System.Threading.Tasks.Task<NorthWind_WebApp.ServiceReference1.Delete_CustomerResponse> Delete_CustomerAsync(NorthWind_WebApp.ServiceReference1.Delete_CustomerRequest request);
        
        // CODEGEN: Generating message contract since element name Cust from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrdersData", ReplyAction="*")]
        NorthWind_WebApp.ServiceReference1.OrdersDataResponse OrdersData(NorthWind_WebApp.ServiceReference1.OrdersDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrdersData", ReplyAction="*")]
        System.Threading.Tasks.Task<NorthWind_WebApp.ServiceReference1.OrdersDataResponse> OrdersDataAsync(NorthWind_WebApp.ServiceReference1.OrdersDataRequest request);
        
        // CODEGEN: Generating message contract since element name CustomerID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlaceOrder", ReplyAction="*")]
        NorthWind_WebApp.ServiceReference1.PlaceOrderResponse PlaceOrder(NorthWind_WebApp.ServiceReference1.PlaceOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlaceOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<NorthWind_WebApp.ServiceReference1.PlaceOrderResponse> PlaceOrderAsync(NorthWind_WebApp.ServiceReference1.PlaceOrderRequest request);
        
        // CODEGEN: Generating message contract since element name AddProductsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddProducts", ReplyAction="*")]
        NorthWind_WebApp.ServiceReference1.AddProductsResponse AddProducts(NorthWind_WebApp.ServiceReference1.AddProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddProducts", ReplyAction="*")]
        System.Threading.Tasks.Task<NorthWind_WebApp.ServiceReference1.AddProductsResponse> AddProductsAsync(NorthWind_WebApp.ServiceReference1.AddProductsRequest request);
        
        // CODEGEN: Generating message contract since element name AddEmployeesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddEmployees", ReplyAction="*")]
        NorthWind_WebApp.ServiceReference1.AddEmployeesResponse AddEmployees(NorthWind_WebApp.ServiceReference1.AddEmployeesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddEmployees", ReplyAction="*")]
        System.Threading.Tasks.Task<NorthWind_WebApp.ServiceReference1.AddEmployeesResponse> AddEmployeesAsync(NorthWind_WebApp.ServiceReference1.AddEmployeesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FirstCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FirstCustomer", Namespace="http://tempuri.org/", Order=0)]
        public NorthWind_WebApp.ServiceReference1.FirstCustomerRequestBody Body;
        
        public FirstCustomerRequest() {
        }
        
        public FirstCustomerRequest(NorthWind_WebApp.ServiceReference1.FirstCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class FirstCustomerRequestBody {
        
        public FirstCustomerRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FirstCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FirstCustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public NorthWind_WebApp.ServiceReference1.FirstCustomerResponseBody Body;
        
        public FirstCustomerResponse() {
        }
        
        public FirstCustomerResponse(NorthWind_WebApp.ServiceReference1.FirstCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FirstCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NorthWind_WebApp.ServiceReference1.Customer FirstCustomerResult;
        
        public FirstCustomerResponseBody() {
        }
        
        public FirstCustomerResponseBody(NorthWind_WebApp.ServiceReference1.Customer FirstCustomerResult) {
            this.FirstCustomerResult = FirstCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LastCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LastCustomer", Namespace="http://tempuri.org/", Order=0)]
        public NorthWind_WebApp.ServiceReference1.LastCustomerRequestBody Body;
        
        public LastCustomerRequest() {
        }
        
        public LastCustomerRequest(NorthWind_WebApp.ServiceReference1.LastCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LastCustomerRequestBody {
        
        public LastCustomerRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LastCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LastCustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public NorthWind_WebApp.ServiceReference1.LastCustomerResponseBody Body;
        
        public LastCustomerResponse() {
        }
        
        public LastCustomerResponse(NorthWind_WebApp.ServiceReference1.LastCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LastCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NorthWind_WebApp.ServiceReference1.Customer LastCustomerResult;
        
        public LastCustomerResponseBody() {
        }
        
        public LastCustomerResponseBody(NorthWind_WebApp.ServiceReference1.Customer LastCustomerResult) {
            this.LastCustomerResult = LastCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NextCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NextCustomer", Namespace="http://tempuri.org/", Order=0)]
        public NorthWind_WebApp.ServiceReference1.NextCustomerRequestBody Body;
        
        public NextCustomerRequest() {
        }
        
        public NextCustomerRequest(NorthWind_WebApp.ServiceReference1.NextCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NextCustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public NextCustomerRequestBody() {
        }
        
        public NextCustomerRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NextCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NextCustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public NorthWind_WebApp.ServiceReference1.NextCustomerResponseBody Body;
        
        public NextCustomerResponse() {
        }
        
        public NextCustomerResponse(NorthWind_WebApp.ServiceReference1.NextCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NextCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NorthWind_WebApp.ServiceReference1.Customer NextCustomerResult;
        
        public NextCustomerResponseBody() {
        }
        
        public NextCustomerResponseBody(NorthWind_WebApp.ServiceReference1.Customer NextCustomerResult) {
            this.NextCustomerResult = NextCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrevCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrevCustomer", Namespace="http://tempuri.org/", Order=0)]
        public NorthWind_WebApp.ServiceReference1.PrevCustomerRequestBody Body;
        
        public PrevCustomerRequest() {
        }
        
        public PrevCustomerRequest(NorthWind_WebApp.ServiceReference1.PrevCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PrevCustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public PrevCustomerRequestBody() {
        }
        
        public PrevCustomerRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrevCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrevCustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public NorthWind_WebApp.ServiceReference1.PrevCustomerResponseBody Body;
        
        public PrevCustomerResponse() {
        }
        
        public PrevCustomerResponse(NorthWind_WebApp.ServiceReference1.PrevCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PrevCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NorthWind_WebApp.ServiceReference1.Customer PrevCustomerResult;
        
        public PrevCustomerResponseBody() {
        }
        
        public PrevCustomerResponseBody(NorthWind_WebApp.ServiceReference1.Customer PrevCustomerResult) {
            this.PrevCustomerResult = PrevCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Add_CustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add_Customer", Namespace="http://tempuri.org/", Order=0)]
        public NorthWind_WebApp.ServiceReference1.Add_CustomerRequestBody Body;
        
        public Add_CustomerRequest() {
        }
        
        public Add_CustomerRequest(NorthWind_WebApp.ServiceReference1.Add_CustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Add_CustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CompName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CustName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CustTitle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Address;
        
        public Add_CustomerRequestBody() {
        }
        
        public Add_CustomerRequestBody(string ID, string CompName, string CustName, string CustTitle, string Address) {
            this.ID = ID;
            this.CompName = CompName;
            this.CustName = CustName;
            this.CustTitle = CustTitle;
            this.Address = Address;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Add_CustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add_CustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public NorthWind_WebApp.ServiceReference1.Add_CustomerResponseBody Body;
        
        public Add_CustomerResponse() {
        }
        
        public Add_CustomerResponse(NorthWind_WebApp.ServiceReference1.Add_CustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Add_CustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool Add_CustomerResult;
        
        public Add_CustomerResponseBody() {
        }
        
        public Add_CustomerResponseBody(bool Add_CustomerResult) {
            this.Add_CustomerResult = Add_CustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Update_CustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update_Customer", Namespace="http://tempuri.org/", Order=0)]
        public NorthWind_WebApp.ServiceReference1.Update_CustomerRequestBody Body;
        
        public Update_CustomerRequest() {
        }
        
        public Update_CustomerRequest(NorthWind_WebApp.ServiceReference1.Update_CustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Update_CustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CompName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CustName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CustTitle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Address;
        
        public Update_CustomerRequestBody() {
        }
        
        public Update_CustomerRequestBody(string ID, string CompName, string CustName, string CustTitle, string Address) {
            this.ID = ID;
            this.CompName = CompName;
            this.CustName = CustName;
            this.CustTitle = CustTitle;
            this.Address = Address;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Update_CustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update_CustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public NorthWind_WebApp.ServiceReference1.Update_CustomerResponseBody Body;
        
        public Update_CustomerResponse() {
        }
        
        public Update_CustomerResponse(NorthWind_WebApp.ServiceReference1.Update_CustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Update_CustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool Update_CustomerResult;
        
        public Update_CustomerResponseBody() {
        }
        
        public Update_CustomerResponseBody(bool Update_CustomerResult) {
            this.Update_CustomerResult = Update_CustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Delete_CustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Customer", Namespace="http://tempuri.org/", Order=0)]
        public NorthWind_WebApp.ServiceReference1.Delete_CustomerRequestBody Body;
        
        public Delete_CustomerRequest() {
        }
        
        public Delete_CustomerRequest(NorthWind_WebApp.ServiceReference1.Delete_CustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Delete_CustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ID;
        
        public Delete_CustomerRequestBody() {
        }
        
        public Delete_CustomerRequestBody(string ID) {
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Delete_CustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_CustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public NorthWind_WebApp.ServiceReference1.Delete_CustomerResponseBody Body;
        
        public Delete_CustomerResponse() {
        }
        
        public Delete_CustomerResponse(NorthWind_WebApp.ServiceReference1.Delete_CustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Delete_CustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool Delete_CustomerResult;
        
        public Delete_CustomerResponseBody() {
        }
        
        public Delete_CustomerResponseBody(bool Delete_CustomerResult) {
            this.Delete_CustomerResult = Delete_CustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OrdersDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OrdersData", Namespace="http://tempuri.org/", Order=0)]
        public NorthWind_WebApp.ServiceReference1.OrdersDataRequestBody Body;
        
        public OrdersDataRequest() {
        }
        
        public OrdersDataRequest(NorthWind_WebApp.ServiceReference1.OrdersDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OrdersDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NorthWind_WebApp.ServiceReference1.Customer Cust;
        
        public OrdersDataRequestBody() {
        }
        
        public OrdersDataRequestBody(NorthWind_WebApp.ServiceReference1.Customer Cust) {
            this.Cust = Cust;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OrdersDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OrdersDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public NorthWind_WebApp.ServiceReference1.OrdersDataResponseBody Body;
        
        public OrdersDataResponse() {
        }
        
        public OrdersDataResponse(NorthWind_WebApp.ServiceReference1.OrdersDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OrdersDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NorthWind_WebApp.ServiceReference1.OrderDetails[] OrdersDataResult;
        
        public OrdersDataResponseBody() {
        }
        
        public OrdersDataResponseBody(NorthWind_WebApp.ServiceReference1.OrderDetails[] OrdersDataResult) {
            this.OrdersDataResult = OrdersDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PlaceOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PlaceOrder", Namespace="http://tempuri.org/", Order=0)]
        public NorthWind_WebApp.ServiceReference1.PlaceOrderRequestBody Body;
        
        public PlaceOrderRequest() {
        }
        
        public PlaceOrderRequest(NorthWind_WebApp.ServiceReference1.PlaceOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PlaceOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CustomerID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int EmployeeID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int ProductID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int Quantity;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public decimal UnitPrice;
        
        public PlaceOrderRequestBody() {
        }
        
        public PlaceOrderRequestBody(string CustomerID, int EmployeeID, int ProductID, int Quantity, decimal UnitPrice) {
            this.CustomerID = CustomerID;
            this.EmployeeID = EmployeeID;
            this.ProductID = ProductID;
            this.Quantity = Quantity;
            this.UnitPrice = UnitPrice;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PlaceOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PlaceOrderResponse", Namespace="http://tempuri.org/", Order=0)]
        public NorthWind_WebApp.ServiceReference1.PlaceOrderResponseBody Body;
        
        public PlaceOrderResponse() {
        }
        
        public PlaceOrderResponse(NorthWind_WebApp.ServiceReference1.PlaceOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PlaceOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool PlaceOrderResult;
        
        public PlaceOrderResponseBody() {
        }
        
        public PlaceOrderResponseBody(bool PlaceOrderResult) {
            this.PlaceOrderResult = PlaceOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddProductsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddProducts", Namespace="http://tempuri.org/", Order=0)]
        public NorthWind_WebApp.ServiceReference1.AddProductsRequestBody Body;
        
        public AddProductsRequest() {
        }
        
        public AddProductsRequest(NorthWind_WebApp.ServiceReference1.AddProductsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddProductsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ProdID;
        
        public AddProductsRequestBody() {
        }
        
        public AddProductsRequestBody(int ProdID) {
            this.ProdID = ProdID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddProductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddProductsResponse", Namespace="http://tempuri.org/", Order=0)]
        public NorthWind_WebApp.ServiceReference1.AddProductsResponseBody Body;
        
        public AddProductsResponse() {
        }
        
        public AddProductsResponse(NorthWind_WebApp.ServiceReference1.AddProductsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddProductsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NorthWind_WebApp.ServiceReference1.Products[] AddProductsResult;
        
        public AddProductsResponseBody() {
        }
        
        public AddProductsResponseBody(NorthWind_WebApp.ServiceReference1.Products[] AddProductsResult) {
            this.AddProductsResult = AddProductsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddEmployeesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddEmployees", Namespace="http://tempuri.org/", Order=0)]
        public NorthWind_WebApp.ServiceReference1.AddEmployeesRequestBody Body;
        
        public AddEmployeesRequest() {
        }
        
        public AddEmployeesRequest(NorthWind_WebApp.ServiceReference1.AddEmployeesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddEmployeesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int EmpID;
        
        public AddEmployeesRequestBody() {
        }
        
        public AddEmployeesRequestBody(int EmpID) {
            this.EmpID = EmpID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddEmployeesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddEmployeesResponse", Namespace="http://tempuri.org/", Order=0)]
        public NorthWind_WebApp.ServiceReference1.AddEmployeesResponseBody Body;
        
        public AddEmployeesResponse() {
        }
        
        public AddEmployeesResponse(NorthWind_WebApp.ServiceReference1.AddEmployeesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddEmployeesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NorthWind_WebApp.ServiceReference1.Employee[] AddEmployeesResult;
        
        public AddEmployeesResponseBody() {
        }
        
        public AddEmployeesResponseBody(NorthWind_WebApp.ServiceReference1.Employee[] AddEmployeesResult) {
            this.AddEmployeesResult = AddEmployeesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : NorthWind_WebApp.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<NorthWind_WebApp.ServiceReference1.WebService1Soap>, NorthWind_WebApp.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NorthWind_WebApp.ServiceReference1.FirstCustomerResponse NorthWind_WebApp.ServiceReference1.WebService1Soap.FirstCustomer(NorthWind_WebApp.ServiceReference1.FirstCustomerRequest request) {
            return base.Channel.FirstCustomer(request);
        }
        
        public NorthWind_WebApp.ServiceReference1.Customer FirstCustomer() {
            NorthWind_WebApp.ServiceReference1.FirstCustomerRequest inValue = new NorthWind_WebApp.ServiceReference1.FirstCustomerRequest();
            inValue.Body = new NorthWind_WebApp.ServiceReference1.FirstCustomerRequestBody();
            NorthWind_WebApp.ServiceReference1.FirstCustomerResponse retVal = ((NorthWind_WebApp.ServiceReference1.WebService1Soap)(this)).FirstCustomer(inValue);
            return retVal.Body.FirstCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NorthWind_WebApp.ServiceReference1.FirstCustomerResponse> NorthWind_WebApp.ServiceReference1.WebService1Soap.FirstCustomerAsync(NorthWind_WebApp.ServiceReference1.FirstCustomerRequest request) {
            return base.Channel.FirstCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<NorthWind_WebApp.ServiceReference1.FirstCustomerResponse> FirstCustomerAsync() {
            NorthWind_WebApp.ServiceReference1.FirstCustomerRequest inValue = new NorthWind_WebApp.ServiceReference1.FirstCustomerRequest();
            inValue.Body = new NorthWind_WebApp.ServiceReference1.FirstCustomerRequestBody();
            return ((NorthWind_WebApp.ServiceReference1.WebService1Soap)(this)).FirstCustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NorthWind_WebApp.ServiceReference1.LastCustomerResponse NorthWind_WebApp.ServiceReference1.WebService1Soap.LastCustomer(NorthWind_WebApp.ServiceReference1.LastCustomerRequest request) {
            return base.Channel.LastCustomer(request);
        }
        
        public NorthWind_WebApp.ServiceReference1.Customer LastCustomer() {
            NorthWind_WebApp.ServiceReference1.LastCustomerRequest inValue = new NorthWind_WebApp.ServiceReference1.LastCustomerRequest();
            inValue.Body = new NorthWind_WebApp.ServiceReference1.LastCustomerRequestBody();
            NorthWind_WebApp.ServiceReference1.LastCustomerResponse retVal = ((NorthWind_WebApp.ServiceReference1.WebService1Soap)(this)).LastCustomer(inValue);
            return retVal.Body.LastCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NorthWind_WebApp.ServiceReference1.LastCustomerResponse> NorthWind_WebApp.ServiceReference1.WebService1Soap.LastCustomerAsync(NorthWind_WebApp.ServiceReference1.LastCustomerRequest request) {
            return base.Channel.LastCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<NorthWind_WebApp.ServiceReference1.LastCustomerResponse> LastCustomerAsync() {
            NorthWind_WebApp.ServiceReference1.LastCustomerRequest inValue = new NorthWind_WebApp.ServiceReference1.LastCustomerRequest();
            inValue.Body = new NorthWind_WebApp.ServiceReference1.LastCustomerRequestBody();
            return ((NorthWind_WebApp.ServiceReference1.WebService1Soap)(this)).LastCustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NorthWind_WebApp.ServiceReference1.NextCustomerResponse NorthWind_WebApp.ServiceReference1.WebService1Soap.NextCustomer(NorthWind_WebApp.ServiceReference1.NextCustomerRequest request) {
            return base.Channel.NextCustomer(request);
        }
        
        public NorthWind_WebApp.ServiceReference1.Customer NextCustomer(string id) {
            NorthWind_WebApp.ServiceReference1.NextCustomerRequest inValue = new NorthWind_WebApp.ServiceReference1.NextCustomerRequest();
            inValue.Body = new NorthWind_WebApp.ServiceReference1.NextCustomerRequestBody();
            inValue.Body.id = id;
            NorthWind_WebApp.ServiceReference1.NextCustomerResponse retVal = ((NorthWind_WebApp.ServiceReference1.WebService1Soap)(this)).NextCustomer(inValue);
            return retVal.Body.NextCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NorthWind_WebApp.ServiceReference1.NextCustomerResponse> NorthWind_WebApp.ServiceReference1.WebService1Soap.NextCustomerAsync(NorthWind_WebApp.ServiceReference1.NextCustomerRequest request) {
            return base.Channel.NextCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<NorthWind_WebApp.ServiceReference1.NextCustomerResponse> NextCustomerAsync(string id) {
            NorthWind_WebApp.ServiceReference1.NextCustomerRequest inValue = new NorthWind_WebApp.ServiceReference1.NextCustomerRequest();
            inValue.Body = new NorthWind_WebApp.ServiceReference1.NextCustomerRequestBody();
            inValue.Body.id = id;
            return ((NorthWind_WebApp.ServiceReference1.WebService1Soap)(this)).NextCustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NorthWind_WebApp.ServiceReference1.PrevCustomerResponse NorthWind_WebApp.ServiceReference1.WebService1Soap.PrevCustomer(NorthWind_WebApp.ServiceReference1.PrevCustomerRequest request) {
            return base.Channel.PrevCustomer(request);
        }
        
        public NorthWind_WebApp.ServiceReference1.Customer PrevCustomer(string id) {
            NorthWind_WebApp.ServiceReference1.PrevCustomerRequest inValue = new NorthWind_WebApp.ServiceReference1.PrevCustomerRequest();
            inValue.Body = new NorthWind_WebApp.ServiceReference1.PrevCustomerRequestBody();
            inValue.Body.id = id;
            NorthWind_WebApp.ServiceReference1.PrevCustomerResponse retVal = ((NorthWind_WebApp.ServiceReference1.WebService1Soap)(this)).PrevCustomer(inValue);
            return retVal.Body.PrevCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NorthWind_WebApp.ServiceReference1.PrevCustomerResponse> NorthWind_WebApp.ServiceReference1.WebService1Soap.PrevCustomerAsync(NorthWind_WebApp.ServiceReference1.PrevCustomerRequest request) {
            return base.Channel.PrevCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<NorthWind_WebApp.ServiceReference1.PrevCustomerResponse> PrevCustomerAsync(string id) {
            NorthWind_WebApp.ServiceReference1.PrevCustomerRequest inValue = new NorthWind_WebApp.ServiceReference1.PrevCustomerRequest();
            inValue.Body = new NorthWind_WebApp.ServiceReference1.PrevCustomerRequestBody();
            inValue.Body.id = id;
            return ((NorthWind_WebApp.ServiceReference1.WebService1Soap)(this)).PrevCustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NorthWind_WebApp.ServiceReference1.Add_CustomerResponse NorthWind_WebApp.ServiceReference1.WebService1Soap.Add_Customer(NorthWind_WebApp.ServiceReference1.Add_CustomerRequest request) {
            return base.Channel.Add_Customer(request);
        }
        
        public bool Add_Customer(string ID, string CompName, string CustName, string CustTitle, string Address) {
            NorthWind_WebApp.ServiceReference1.Add_CustomerRequest inValue = new NorthWind_WebApp.ServiceReference1.Add_CustomerRequest();
            inValue.Body = new NorthWind_WebApp.ServiceReference1.Add_CustomerRequestBody();
            inValue.Body.ID = ID;
            inValue.Body.CompName = CompName;
            inValue.Body.CustName = CustName;
            inValue.Body.CustTitle = CustTitle;
            inValue.Body.Address = Address;
            NorthWind_WebApp.ServiceReference1.Add_CustomerResponse retVal = ((NorthWind_WebApp.ServiceReference1.WebService1Soap)(this)).Add_Customer(inValue);
            return retVal.Body.Add_CustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NorthWind_WebApp.ServiceReference1.Add_CustomerResponse> NorthWind_WebApp.ServiceReference1.WebService1Soap.Add_CustomerAsync(NorthWind_WebApp.ServiceReference1.Add_CustomerRequest request) {
            return base.Channel.Add_CustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<NorthWind_WebApp.ServiceReference1.Add_CustomerResponse> Add_CustomerAsync(string ID, string CompName, string CustName, string CustTitle, string Address) {
            NorthWind_WebApp.ServiceReference1.Add_CustomerRequest inValue = new NorthWind_WebApp.ServiceReference1.Add_CustomerRequest();
            inValue.Body = new NorthWind_WebApp.ServiceReference1.Add_CustomerRequestBody();
            inValue.Body.ID = ID;
            inValue.Body.CompName = CompName;
            inValue.Body.CustName = CustName;
            inValue.Body.CustTitle = CustTitle;
            inValue.Body.Address = Address;
            return ((NorthWind_WebApp.ServiceReference1.WebService1Soap)(this)).Add_CustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NorthWind_WebApp.ServiceReference1.Update_CustomerResponse NorthWind_WebApp.ServiceReference1.WebService1Soap.Update_Customer(NorthWind_WebApp.ServiceReference1.Update_CustomerRequest request) {
            return base.Channel.Update_Customer(request);
        }
        
        public bool Update_Customer(string ID, string CompName, string CustName, string CustTitle, string Address) {
            NorthWind_WebApp.ServiceReference1.Update_CustomerRequest inValue = new NorthWind_WebApp.ServiceReference1.Update_CustomerRequest();
            inValue.Body = new NorthWind_WebApp.ServiceReference1.Update_CustomerRequestBody();
            inValue.Body.ID = ID;
            inValue.Body.CompName = CompName;
            inValue.Body.CustName = CustName;
            inValue.Body.CustTitle = CustTitle;
            inValue.Body.Address = Address;
            NorthWind_WebApp.ServiceReference1.Update_CustomerResponse retVal = ((NorthWind_WebApp.ServiceReference1.WebService1Soap)(this)).Update_Customer(inValue);
            return retVal.Body.Update_CustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NorthWind_WebApp.ServiceReference1.Update_CustomerResponse> NorthWind_WebApp.ServiceReference1.WebService1Soap.Update_CustomerAsync(NorthWind_WebApp.ServiceReference1.Update_CustomerRequest request) {
            return base.Channel.Update_CustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<NorthWind_WebApp.ServiceReference1.Update_CustomerResponse> Update_CustomerAsync(string ID, string CompName, string CustName, string CustTitle, string Address) {
            NorthWind_WebApp.ServiceReference1.Update_CustomerRequest inValue = new NorthWind_WebApp.ServiceReference1.Update_CustomerRequest();
            inValue.Body = new NorthWind_WebApp.ServiceReference1.Update_CustomerRequestBody();
            inValue.Body.ID = ID;
            inValue.Body.CompName = CompName;
            inValue.Body.CustName = CustName;
            inValue.Body.CustTitle = CustTitle;
            inValue.Body.Address = Address;
            return ((NorthWind_WebApp.ServiceReference1.WebService1Soap)(this)).Update_CustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NorthWind_WebApp.ServiceReference1.Delete_CustomerResponse NorthWind_WebApp.ServiceReference1.WebService1Soap.Delete_Customer(NorthWind_WebApp.ServiceReference1.Delete_CustomerRequest request) {
            return base.Channel.Delete_Customer(request);
        }
        
        public bool Delete_Customer(string ID) {
            NorthWind_WebApp.ServiceReference1.Delete_CustomerRequest inValue = new NorthWind_WebApp.ServiceReference1.Delete_CustomerRequest();
            inValue.Body = new NorthWind_WebApp.ServiceReference1.Delete_CustomerRequestBody();
            inValue.Body.ID = ID;
            NorthWind_WebApp.ServiceReference1.Delete_CustomerResponse retVal = ((NorthWind_WebApp.ServiceReference1.WebService1Soap)(this)).Delete_Customer(inValue);
            return retVal.Body.Delete_CustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NorthWind_WebApp.ServiceReference1.Delete_CustomerResponse> NorthWind_WebApp.ServiceReference1.WebService1Soap.Delete_CustomerAsync(NorthWind_WebApp.ServiceReference1.Delete_CustomerRequest request) {
            return base.Channel.Delete_CustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<NorthWind_WebApp.ServiceReference1.Delete_CustomerResponse> Delete_CustomerAsync(string ID) {
            NorthWind_WebApp.ServiceReference1.Delete_CustomerRequest inValue = new NorthWind_WebApp.ServiceReference1.Delete_CustomerRequest();
            inValue.Body = new NorthWind_WebApp.ServiceReference1.Delete_CustomerRequestBody();
            inValue.Body.ID = ID;
            return ((NorthWind_WebApp.ServiceReference1.WebService1Soap)(this)).Delete_CustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NorthWind_WebApp.ServiceReference1.OrdersDataResponse NorthWind_WebApp.ServiceReference1.WebService1Soap.OrdersData(NorthWind_WebApp.ServiceReference1.OrdersDataRequest request) {
            return base.Channel.OrdersData(request);
        }
        
        public NorthWind_WebApp.ServiceReference1.OrderDetails[] OrdersData(NorthWind_WebApp.ServiceReference1.Customer Cust) {
            NorthWind_WebApp.ServiceReference1.OrdersDataRequest inValue = new NorthWind_WebApp.ServiceReference1.OrdersDataRequest();
            inValue.Body = new NorthWind_WebApp.ServiceReference1.OrdersDataRequestBody();
            inValue.Body.Cust = Cust;
            NorthWind_WebApp.ServiceReference1.OrdersDataResponse retVal = ((NorthWind_WebApp.ServiceReference1.WebService1Soap)(this)).OrdersData(inValue);
            return retVal.Body.OrdersDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NorthWind_WebApp.ServiceReference1.OrdersDataResponse> NorthWind_WebApp.ServiceReference1.WebService1Soap.OrdersDataAsync(NorthWind_WebApp.ServiceReference1.OrdersDataRequest request) {
            return base.Channel.OrdersDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<NorthWind_WebApp.ServiceReference1.OrdersDataResponse> OrdersDataAsync(NorthWind_WebApp.ServiceReference1.Customer Cust) {
            NorthWind_WebApp.ServiceReference1.OrdersDataRequest inValue = new NorthWind_WebApp.ServiceReference1.OrdersDataRequest();
            inValue.Body = new NorthWind_WebApp.ServiceReference1.OrdersDataRequestBody();
            inValue.Body.Cust = Cust;
            return ((NorthWind_WebApp.ServiceReference1.WebService1Soap)(this)).OrdersDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NorthWind_WebApp.ServiceReference1.PlaceOrderResponse NorthWind_WebApp.ServiceReference1.WebService1Soap.PlaceOrder(NorthWind_WebApp.ServiceReference1.PlaceOrderRequest request) {
            return base.Channel.PlaceOrder(request);
        }
        
        public bool PlaceOrder(string CustomerID, int EmployeeID, int ProductID, int Quantity, decimal UnitPrice) {
            NorthWind_WebApp.ServiceReference1.PlaceOrderRequest inValue = new NorthWind_WebApp.ServiceReference1.PlaceOrderRequest();
            inValue.Body = new NorthWind_WebApp.ServiceReference1.PlaceOrderRequestBody();
            inValue.Body.CustomerID = CustomerID;
            inValue.Body.EmployeeID = EmployeeID;
            inValue.Body.ProductID = ProductID;
            inValue.Body.Quantity = Quantity;
            inValue.Body.UnitPrice = UnitPrice;
            NorthWind_WebApp.ServiceReference1.PlaceOrderResponse retVal = ((NorthWind_WebApp.ServiceReference1.WebService1Soap)(this)).PlaceOrder(inValue);
            return retVal.Body.PlaceOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NorthWind_WebApp.ServiceReference1.PlaceOrderResponse> NorthWind_WebApp.ServiceReference1.WebService1Soap.PlaceOrderAsync(NorthWind_WebApp.ServiceReference1.PlaceOrderRequest request) {
            return base.Channel.PlaceOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<NorthWind_WebApp.ServiceReference1.PlaceOrderResponse> PlaceOrderAsync(string CustomerID, int EmployeeID, int ProductID, int Quantity, decimal UnitPrice) {
            NorthWind_WebApp.ServiceReference1.PlaceOrderRequest inValue = new NorthWind_WebApp.ServiceReference1.PlaceOrderRequest();
            inValue.Body = new NorthWind_WebApp.ServiceReference1.PlaceOrderRequestBody();
            inValue.Body.CustomerID = CustomerID;
            inValue.Body.EmployeeID = EmployeeID;
            inValue.Body.ProductID = ProductID;
            inValue.Body.Quantity = Quantity;
            inValue.Body.UnitPrice = UnitPrice;
            return ((NorthWind_WebApp.ServiceReference1.WebService1Soap)(this)).PlaceOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NorthWind_WebApp.ServiceReference1.AddProductsResponse NorthWind_WebApp.ServiceReference1.WebService1Soap.AddProducts(NorthWind_WebApp.ServiceReference1.AddProductsRequest request) {
            return base.Channel.AddProducts(request);
        }
        
        public NorthWind_WebApp.ServiceReference1.Products[] AddProducts(int ProdID) {
            NorthWind_WebApp.ServiceReference1.AddProductsRequest inValue = new NorthWind_WebApp.ServiceReference1.AddProductsRequest();
            inValue.Body = new NorthWind_WebApp.ServiceReference1.AddProductsRequestBody();
            inValue.Body.ProdID = ProdID;
            NorthWind_WebApp.ServiceReference1.AddProductsResponse retVal = ((NorthWind_WebApp.ServiceReference1.WebService1Soap)(this)).AddProducts(inValue);
            return retVal.Body.AddProductsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NorthWind_WebApp.ServiceReference1.AddProductsResponse> NorthWind_WebApp.ServiceReference1.WebService1Soap.AddProductsAsync(NorthWind_WebApp.ServiceReference1.AddProductsRequest request) {
            return base.Channel.AddProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<NorthWind_WebApp.ServiceReference1.AddProductsResponse> AddProductsAsync(int ProdID) {
            NorthWind_WebApp.ServiceReference1.AddProductsRequest inValue = new NorthWind_WebApp.ServiceReference1.AddProductsRequest();
            inValue.Body = new NorthWind_WebApp.ServiceReference1.AddProductsRequestBody();
            inValue.Body.ProdID = ProdID;
            return ((NorthWind_WebApp.ServiceReference1.WebService1Soap)(this)).AddProductsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NorthWind_WebApp.ServiceReference1.AddEmployeesResponse NorthWind_WebApp.ServiceReference1.WebService1Soap.AddEmployees(NorthWind_WebApp.ServiceReference1.AddEmployeesRequest request) {
            return base.Channel.AddEmployees(request);
        }
        
        public NorthWind_WebApp.ServiceReference1.Employee[] AddEmployees(int EmpID) {
            NorthWind_WebApp.ServiceReference1.AddEmployeesRequest inValue = new NorthWind_WebApp.ServiceReference1.AddEmployeesRequest();
            inValue.Body = new NorthWind_WebApp.ServiceReference1.AddEmployeesRequestBody();
            inValue.Body.EmpID = EmpID;
            NorthWind_WebApp.ServiceReference1.AddEmployeesResponse retVal = ((NorthWind_WebApp.ServiceReference1.WebService1Soap)(this)).AddEmployees(inValue);
            return retVal.Body.AddEmployeesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NorthWind_WebApp.ServiceReference1.AddEmployeesResponse> NorthWind_WebApp.ServiceReference1.WebService1Soap.AddEmployeesAsync(NorthWind_WebApp.ServiceReference1.AddEmployeesRequest request) {
            return base.Channel.AddEmployeesAsync(request);
        }
        
        public System.Threading.Tasks.Task<NorthWind_WebApp.ServiceReference1.AddEmployeesResponse> AddEmployeesAsync(int EmpID) {
            NorthWind_WebApp.ServiceReference1.AddEmployeesRequest inValue = new NorthWind_WebApp.ServiceReference1.AddEmployeesRequest();
            inValue.Body = new NorthWind_WebApp.ServiceReference1.AddEmployeesRequestBody();
            inValue.Body.EmpID = EmpID;
            return ((NorthWind_WebApp.ServiceReference1.WebService1Soap)(this)).AddEmployeesAsync(inValue);
        }
    }
}
